# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      test:
        executor: node/default
          steps:
            - checkout
            - node/install-packages: 
              override-ci-command: npm install        
            - run: npm test
