# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@4.5
  heroku: circleci/heroku@1.2.6
jobs:
  test-frontend:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: "cd frontend && npm install"
      - run: npm run coverage
      - store_artifacts:
          path: coverage
          destination: circleci-docs
  test-backend:
    docker:  
      - image: cimg/node:17.4.0
      - image: cimg/postgres:14.1
    steps:
      - checkout      
      - node/install-packages:
          override-ci-command: npm install
      - run: "cd backend && npx dotenv sequelize-cli db:create && npm run test"
      - run: npm run coverage

workflows:
  test:
    jobs:
      - test-frontend:
        filters:
          branches:
            ignore: main
      - test-backend:
        filters:
          branches:
            ignore: main
  deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main
