# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'
orbs:
  node: circleci/node@4.5
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:          
          override-ci-command: npm install
      - run: npm run test

workflows:
  test_my_app:
    jobs:
      - test
  workflows:
    heroku_deploy:
      jobs:
        - build
        - heroku/deploy-via-git:
            requires:
              - build # only run deploy-via-git job if the build job has completed
            filters:
              branches:
                only: master # only run deploy-via-git job on master branch