# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'
orbs:
  node: circleci/node@4.5
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:          
          override-ci-command: npm install
      - run: npm run coverage
      - store_artifacts:
          path: coverage
workflows:  
  heroku_deploy:
    jobs:
      - test       
      - heroku/deploy-via-git:
          requires:
            - test            
          filters:
            branches:
              only: main